on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#prettier -- --print-width 100 --check README.md
      - run: nix run nixpkgs#shfmt -- --posix --indent 4 --diff .
      - run: nix run nixpkgs#shellcheck -- -s sh *.sh
      - run: nix shell nixpkgs#sqlite --command ./test.sh
